### PR TITLE
pash: Add optional git support

### PR DESCRIPTION
**Pull request by frncsdrk**

### CODE REVIEW

**Comment by dylanaraps** [comment]
I don't understand why this needs to be a part of `pash` itself. :)

The password store is simply a directory tree. Basic scripts, shell aliases or shell functions can be written to interact with the store in whatever way you see fit.

As a user, you can simply add the following function to your `.shellrc`. This mimics the functionality in this PR 1:1 and can also be further extended to add whatever else you may like. Much more flexible. :)

```sh
pash() {
    case $1 in
        g*)
            cd "${PASH_DIR:=${XDG_DATA_HOME:=$HOME/.local/share}/pash}"
            shift
            git "$@"
        ;;

        *)
            command pash "$@"
        ;;
    esac
}
```

**Comment by frncsdrk** [comment]
Yes, that is indeed a great option! Had not thought about that. Could you add this to the readme for awareness? I think having the possibility of using git might be important for a lot of people coming from `pass`.

**Comment by dylanaraps** [comment]
Done. :)

**Comment by frncsdrk** [comment]
Great! Thank you!

**Pull request closed without merging**
